language: android

android:
    components:
        - android-22
        - tools
        - platform-tools
        - build-tools-24.0.0
        - extra

before_install:
    - sudo chmod +x ./gradlew

script: ./gradlew clean build